version: '3'

services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    links: [database]
    ports: ['8181:80']
    volumes:
      - ./core:/var/www/html
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    depends_on:
      - database
    environment:
      - DB_SERVER=database.svc:3306
      - MW_ADMIN_NAME=admin
      - MW_ADMIN_PASS=adminpass
      - MW_WG_SECRET_KEY=secretkey
      - DB_USER=wikiuser
      - DB_PASS=sqlpass
      - DB_NAME=boxwiki
      - MW_SITE_NAME=box
      - MW_SITE_LANG=en
  database:
    image: mariadb
    volumes: ['./mysql:/var/lib/mysql']
    environment:
      MYSQL_DATABASE: boxwiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: sqlpass
      MYSQL_ROOT_PASSWORD: sqlrootpass
    networks:
      default:
        aliases:
          - database.svc
